#!/usr/bin/env bash

set -ueo pipefail
shopt -s nullglob

: "${XDG_CONFIG_HOME:=$HOME/.local/share}"
readonly DEFAULT_CONFIGFILE="$XDG_CONFIG_HOME/bkp/config"

readonly CONFIGFILE="${CONFIGFILE:=$DEFAULT_CONFIGFILE}"

readonly EXIT_SUCCESS=0
readonly EXIT_FAILURE=1

die() {
    local program_name
    program_name="$(basename "$0")"
    echo "$program_name: Error: $1" 1>&2
    exit "${2:-$EXIT_FAILURE}"
}

check_configfile() {
    if [ ! -r "$CONFIGFILE" ]; then
        die "CONFIGFILE(=$CONFIGFILE) not found" 1
    fi
}

load_config() {
    source "$CONFIGFILE"
}

_is_variable_set() {
    [[ -v "$1" ]]
}

_is_directory() {
    [[ -d "$1" ]]
}

_directory_writable() {
    [[ -w "$1" ]]
}

get_backup_dirs() {
    echo "${BACKUP_DIRECTORIES[*]}"
}

_check_backup_dirs() {
    local backup_dir
    for backup_dir in $(get_backup_dirs)
    do
        if ! _is_directory "$backup_dir"; then
            die "Config is invalid: '$backup_dir' is not a directory" 1
        fi
        if ! _directory_writable "$backup_dir"; then
            die "Config is invalid: '$backup_dir' is not writable" 1
        fi
    done
}

check_config() {
    if ! _is_variable_set "ROOT_BACKUP_DIRECTORY"; then
        die "Config is invalid: variable ROOT_BACKUP_DIRECTORY not set" 1
    fi

    if ! _is_variable_set "BACKUP_DIRECTORIES"; then
        die "Config is invalid: variable BACKUP_DIRECTORIES not set" 1
    fi

    if ! _is_directory "$ROOT_BACKUP_DIRECTORY"; then
        die "Config is invalid: ROOT_BACKUP_DIRECTORY(=$ROOT_BACKUP_DIRECTORY) is not a directory" 1
    fi

    _check_backup_dirs
}

sync_root_with() {
    rsync -ra "$ROOT_BACKUP_DIRECTORY"/* "$ROOT_BACKUP_DIRECTORY"/.* "$1"
}

cmd_sync_all() {
    for i in $(get_backup_dirs)
    do
        sync_root_with "$i"
    done
}


check_configfile
load_config
check_config


case "$1" in
    sync) shift;  cmd_sync_all ;;

    *)            die "No command specified" 0    ;;
esac
exit $EXIT_SUCCESS